---
title: "First Knit"
author: "Heydee Martinez"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I attended Palmdale High School and graduated in 2022. I think I'm more proficient in English and English is much easier for me than math. I was apart of the med academy in high school and I think did my best in the medical terminology class.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
The computer I use is a Microsoft Surface 5 (windows). On a scale from 1 to 10 I would rate myself a 6 in my computer skills. I'm not super knowledgeable but I can figure out most problems and settings. My internet connection at home is pretty solid and reliable. It can be spotty at times but that's rare.  
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
 I would perfer if everyone used my first name "Heydee." I mostly use my first name and some people us my nickname yoli because of my middle name Yolotzin. Either name is fine for me. 
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
 I'm not super set on a career yet. I'm currently majoring in Political Science and enjoying it quite a bit. I'm currently going after my bachelors degree. I'm not sure where life will take me and if I decide to attend law school. If I don't continue for my JD; I can see myself in a policy analyst type of job. 
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
 I have been to some foreign countries. My family is from Mexico so I visit there often. But I was also very lucky to have had the opportunity to travel to Europe in high school with my choir group. I went for a competion but I was able to visit England (London, Cambridge, Stratford upon Avon) and Wales. It was an amazing oppurtunity that sparked my love for travel.
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




